type Query {
    allUsers: [zenUser!]!
    userById(id: ID!): zenUser
    userByUsername(username: String!): zenUser
    userByEmail(email: String!): zenUser

    #TimeBlocks
    userTimeBlocks(userId: ID!): [TimeBlock!]!
}

type Mutation {
    signUp(input: SignUpInput!): zenUser!
    updateUser(id: ID!, input: UpdateUserInput): zenUser!
    deleteUser(id: ID!): zenUser!
    confirmUser(token: String!): Boolean!

    #TimeBlocks
    updateTimeBlockPositions(timeBlocks: [TimeBlockInput!]!): Boolean!
}