spring.application.name=AuraCalmBackend

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wayneragsac@gmail.com
spring.mail.password=wjrovzmvwidavlhm 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.confirmation-url=https://yourfrontend.com/confirm?token=

app.email.confirmation.enabled=true
app.email.confirmation.expiration-hours=24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

resend.api.key=${RESEND_API_KEY}
